version: '3'
services:
  hipcad_redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
  hipcad_web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - '3022:3022'
    expose:
      - '3022'
    volumes:
      - ./log:/app/log/
    depends_on:
      - hipcad_redis
    links:
      - hipcad_redis